import { QueryClient } from '@tanstack/react-query'
import { createRouter } from '@tanstack/react-router'
import { setupRouterSsrQueryIntegration } from '@tanstack/react-router-ssr-query'
import { routeTree } from './routeTree.gen'

// routeTree.gen.ts is generated by the TanStack Start vite plugin on first `dev`/`build`.
export function getRouter() {
  // QueryClient is created PER router instance (inside the factory) — a module-level
  // singleton would leak cached data across SSR requests.
  const queryClient = new QueryClient({
    defaultOptions: { queries: { staleTime: 30_000 } },
  })

  const router = createRouter({
    routeTree,
    context: { queryClient },
    defaultPreload: 'intent',
    // Let React Query own caching; keep the router's preload cache out of the way.
    defaultPreloadStaleTime: 0,
    scrollRestoration: true,
  })

  // Wires SSR dehydration/hydration/streaming and injects QueryClientProvider via
  // router.options.Wrap (so no manual provider in __root).
  setupRouterSsrQueryIntegration({ router, queryClient })

  return router
}

declare module '@tanstack/react-router' {
  interface Register {
    router: ReturnType<typeof getRouter>
  }
}
