import { betterAuth } from 'better-auth'
import type { BetterAuthPlugin } from 'better-auth'
import { drizzleAdapter } from 'better-auth/adapters/drizzle'
import { organization } from 'better-auth/plugins'
import { schema } from '@overstory/db'
import type { Db } from '@overstory/db'

// Shared Better Auth config (D37): ONE config, instantiated in each server (api + web)
// with that server's own db. Same BETTER_AUTH_SECRET + same DB means a session minted on
// the web origin is valid wherever the cookie is sent. The AUTH schema is generated by the
// Better Auth CLI from this config (organization plugin -> organization = Workspace, D23/D26).
//
// Regenerate the Drizzle auth tables after changing plugins/fields (the CLI needs a
// concrete `auth` instance, so point it at apps/api/src/lib/auth.ts, not this factory):
//   DATABASE_URL=postgresql://localhost/x \
//     pnpm dlx @better-auth/cli@latest generate \
//       --config apps/api/src/lib/auth.ts \
//       --output packages/db/src/schema/auth.ts -y
export function createAuth(db: Db, opts: { baseURL?: string; plugins?: BetterAuthPlugin[] } = {}) {
  // Hard dependency: better-auth silently falls back to a weak generated dev secret if this
  // is unset (warns, does not throw), which would mean forgeable sessions in prod. Fail loud.
  const secret = process.env.BETTER_AUTH_SECRET
  if (!secret) throw new Error('BETTER_AUTH_SECRET is required')
  return betterAuth({
    database: drizzleAdapter(db, { provider: 'pg', schema }),
    secret,
    // Each origin sets its own baseURL (web :3000, api :3001); falls back to env.
    baseURL: opts.baseURL ?? process.env.BETTER_AUTH_URL,
    emailAndPassword: { enabled: true },
    // organization defines the schema (Workspace); extra plugins are origin-specific
    // (the web adds tanstackStartCookies, which must come LAST). Schema is generated
    // from the api instance, so origin-only plugins must not add tables.
    plugins: [organization(), ...(opts.plugins ?? [])],
  })
}

export type Auth = ReturnType<typeof createAuth>
