import { betterAuth } from 'better-auth'
import type { BetterAuthPlugin } from 'better-auth'
import { drizzleAdapter } from 'better-auth/adapters/drizzle'
import { organization } from 'better-auth/plugins'
import { env, requireEnv } from '@overstory/config'
import { schema } from '@overstory/db'
import type { Db } from '@overstory/db'

// Shared Better Auth config (D37): ONE config, instantiated in each server (api + web)
// with that server's own db. Same BETTER_AUTH_SECRET + same DB means a session minted on
// the web origin is valid wherever the cookie is sent. The AUTH schema is generated by the
// Better Auth CLI from this config (organization plugin -> organization = Workspace, D23/D26).
//
// Regenerate the Drizzle auth tables after changing plugins/fields (the CLI needs a
// concrete `auth` instance, so point it at apps/api/src/lib/auth.ts, not this factory):
//   DATABASE_URL=postgresql://localhost/x \
//     pnpm dlx @better-auth/cli@latest generate \
//       --config apps/api/src/lib/auth.ts \
//       --output packages/db/src/schema/auth.ts -y
export function createAuth(db: Db, opts: { baseURL?: string; plugins?: BetterAuthPlugin[] } = {}) {
  // requireEnv fails loud if BETTER_AUTH_SECRET is unset (better-auth would otherwise use a
  // weak generated dev secret → forgeable sessions in prod). Env checks live in @overstory/config.
  const secret = requireEnv('BETTER_AUTH_SECRET')
  // Explicit origin allowlist for the cookie auth endpoints (CSRF backstop). D37 runs two
  // origins (web :3000 + api :3001) on ONE secret+DB, so each must trust the other; without
  // this Better Auth defaults to baseURL-only. Only set when non-empty (audit H5).
  const trustedOrigins = [
    ...new Set(
      [opts.baseURL, env.WEB_BASE_URL, env.BETTER_AUTH_URL].filter((u): u is string => Boolean(u)),
    ),
  ]
  return betterAuth({
    database: drizzleAdapter(db, { provider: 'pg', schema }),
    secret,
    // Each origin sets its own baseURL (web :3000, api :3001); falls back to env.
    baseURL: opts.baseURL ?? env.BETTER_AUTH_URL,
    ...(trustedOrigins.length > 0 ? { trustedOrigins } : {}),
    // Built-in throttle on the auth endpoints (brute-force backstop). Better Auth defaults this
    // OFF outside production; enable it everywhere. In-memory store suits one instance — a
    // shared store lands with multi-instance deploy (audit H2).
    rateLimit: { enabled: true },
    // Sign-up is CLOSED by default: resolveDashCtx (apps/web) still serves the single seeded
    // workspace regardless of who logs in (session-derived tenant scope is the D36 follow-up),
    // so an open sign-up form lets any self-registered stranger read the dogfood tenant's
    // decisions + activity. Gate behind OVERSTORY_OPEN_SIGNUP="true" (mint the operator account,
    // then unset). Remove this gate when D36 lands session→workspace scope. See audit C1.
    emailAndPassword: { enabled: true, disableSignUp: env.OVERSTORY_OPEN_SIGNUP !== 'true' },
    // organization defines the schema (Workspace); any origin-specific plugins are appended
    // LAST via opts.plugins. The web sets its auth cookies by forwarding Better Auth's
    // Set-Cookie Response through the /api/auth/$ catch-all route (no plugin needed today); if
    // it ever sets cookies from inside a createServerFn instead, pass tanstackStartCookies()
    // here (from better-auth/integrations/tanstack-start) — it must come last. Schema is
    // generated from the api instance, so origin-only plugins must not add tables.
    plugins: [organization(), ...(opts.plugins ?? [])],
  })
}

export type Auth = ReturnType<typeof createAuth>
