// Drizzle schema. Auth tables are generated by Better Auth (auth.ts — do not hand-edit);
// domain tables are hand-defined. See docs/technical/data-model.md.

// Auth (Better Auth): user, session, account, verification, organization (= Workspace),
// member, invitation, and their relations.
export * from './auth'

// Domain tables
export * from './repo'
export * from './repo-access'
export * from './api-key'
export * from './flow'
export * from './decision'
export * from './pointer'
export * from './analysis-artifact'
export * from './provocation'
export * from './contradiction-event'
export * from './serve-event'

// Domain relations
export * from './relations'

// Shared types (branded ids, enums, jsonb shapes)
export * from './_ids'
export * from './_enums'
export * from './_types'
